trigger: none # Disable CI triggers for this pipeline

resources:
  pipelines:
    - pipeline: ciPipeline
      source: test2 # Replace with your CI pipeline name
      trigger:
        branches:
          include:
            - refs/tags/R1.0.0


steps:
- script: |
    echo $(resources.pipeline.myresourcevars.pipelineID)
