trigger: none

resources:
  pipelines:
  - pipeline: test2
    source: test2
    trigger:
      branches:
        include:
         - refs/tags/R1.0.0
        exclude:
         - '*'

steps:
- script: |
    echo $(resources.pipeline.myresourcevars.pipelineID)
